# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StartSwift04' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StartSwift04
    pod 'Alamofire', '~> 4.5'
    pod 'SnapKit', '~> 4.0.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'HandyJSON', '~> 4.1.1'


end
